# Generated by Django 5.0.1 on 2024-03-28 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('rus_title', models.CharField(max_length=50, verbose_name='Название на русском')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название/Краткое описание изображения')),
                ('url', models.URLField(max_length=300, verbose_name='Ссылка на изображение')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(max_length=300, verbose_name='Описание')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('chat_link', models.URLField(verbose_name='Ссылка на чат')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.image')),
                ('tags', models.ManyToManyField(db_table='event_to_tag', to='main.tag')),
            ],
        ),
    ]
