# Generated by Django 5.0.1 on 2024-04-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
